# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wAUC_sorted <- function(x, y, w) {
    .Call(`_ImbTreeAUC_wAUC_sorted`, x, y, w)
}

AUC_sorted <- function(x, y) {
    .Call(`_ImbTreeAUC_AUC_sorted`, x, y)
}

